In [4]:
import numpy as np
one_d = np.arange(1, 11)
two_d = one_d.reshape(5, 2)

print("1D Tensor:", one_d)
print("2D Tensor:\n", two_d)


1D Tensor: [ 1  2  3  4  5  6  7  8  9 10]
2D Tensor:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [5]:
three_d = np.random.randint(0, 10, (2, 3, 4))
print("3D Tensor:\n", three_d)

3D Tensor:
 [[[9 6 7 5]
  [9 6 3 2]
  [7 0 1 1]]

 [[0 4 5 1]
  [7 2 5 4]
  [7 8 8 3]]]


In [6]:
import tensorflow as tf

ones_tensor = tf.ones((3, 3))
added = ones_tensor + 5
multiplied = added * 3

print("Original Tensor:\n", ones_tensor.numpy())
print("After Adding 5:\n", added.numpy())
print("After Multiplying by 3:\n", multiplied.numpy())


Original Tensor:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After Adding 5:
 [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
After Multiplying by 3:
 [[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]]


In [7]:
def tf_dot_product(a, b):
    return tf.matmul(a, b)

tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])
result = tf_dot_product(tensor_a, tensor_b)
print("Dot Product Result:\n", result.numpy())


Dot Product Result:
 [[19 22]
 [43 50]]


In [8]:
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])
product = np.dot(matrix1, matrix2)
print("Matrix Product:\n", product)


Matrix Product:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [9]:
def slice_tensor(tensor):
    return tensor[:2, :, -1]
sample_3d = np.random.randint(0, 10, (3, 4, 5))

print("Sliced Tensor:\n", slice_tensor(sample_3d))


Sliced Tensor:
 [[1 5 9 9]
 [6 8 5 9]]


In [10]:
zeros = tf.zeros((4, 4))
ones = tf.ones((4, 4))
concatenated = tf.concat([zeros, ones], axis=0)

print("Concatenated Tensor Shape:", concatenated.shape)


Concatenated Tensor Shape: (8, 4)


In [12]:
import tensorflow as tf

zero_tensor = tf.Variable(tf.zeros((5, 5)))
zero_tensor[1:4, 1:4].assign(tf.ones((3, 3)))

print("Modified Tensor:\n", zero_tensor.numpy())


Modified Tensor:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
zero_tensor = tf.zeros((5, 5))
indices = tf.constant([[1,1], [1,2], [1,3],
                      [2,1], [2,2], [2,3],
                      [3,1], [3,2], [3,3]])

updated = tf.tensor_scatter_nd_update(
    zero_tensor,
    indices,
    tf.ones(9)
)
print(updated.numpy())


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
tensor_4x4 = np.random.randint(0, 10, (4, 4))
subtracted = tensor_4x4 - 3
reshaped = subtracted.reshape(2, 8)
print("Subtracted Tensor:\n", subtracted)
print("Reshaped Tensor:\n", reshaped)


Subtracted Tensor:
 [[ 1  5  3  2]
 [ 6  6  3 -1]
 [ 1  5 -3  1]
 [-1  6 -1 -2]]
Reshaped Tensor:
 [[ 1  5  3  2  6  6  3 -1]
 [ 1  5 -3  1 -1  6 -1 -2]]


In [15]:
random_tensor = tf.random.uniform((2, 2), 0, 10, dtype=tf.int32)
subtracted = random_tensor - 3
print("Original Tensor:\n", random_tensor.numpy())
print("After Subtraction:\n", subtracted.numpy())


Original Tensor:
 [[2 6]
 [8 7]]
After Subtraction:
 [[-1  3]
 [ 5  4]]
